<?php

namespace Cittando\SiteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IpCountryRegionCityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IpCountryRegionCityRepository extends EntityRepository
{
    public function getIpCountryRegionCity($ip)
    {
        if(isset($ip)){

            $ip = $this->dot2LongIP($ip);
            $em = $this->getEntityManager();
            $qb = $em->createQueryBuilder();

            $qb->select("ipc")
                ->from("CittandoSiteBundle:IpCountryRegionCity", "ipc")
                ->where(":ip <= ipc.ipTo")
                ->setParameter("ip", $ip)
                ->setMaxResults(1);

            $query = $qb->getQuery($qb);

            return $query->getResult();
        }else{
            return null;
        }
    }

    // Convert dotted IP address into IP number in long
    public function dot2LongIP($ipAddr)
    {
        if ($ipAddr == ""){
            return 0;
        }else{
            $ips = explode('.',$ipAddr);
            return ($ips[3] + $ips[2] * 256 + $ips[1] * 256 * 256 + $ips[0] * 256 * 256 * 256);
        }
    }
}
